services:
  jaeger:
    image: ${REGISTRY:-}jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    environment:
      - LOG_LEVEL=debug
  postgres:
    image: postgis/postgis:17-3.5-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  pdf_api:
    image: ghcr.io/connorvoisey/pdf_api:latest
    ports:
      - '3000:3000'

volumes:
  postgres:
    driver: local
  localstack:
    driver: local
